theme: jekyll-theme-chirpy

lang: en
timezone: Europe/London

# Site settings
title: FinBytes
tagline: "Quantitative Finance & Software Engineering"
description: >-
  Just a documentary learning blog.
url: "https://mish-codes.github.io"
baseurl: "/FinBytes"

github:
  username: mish-codes

# Chirpy-specific
avatar: /assets/images/logo.png

social:
  name: mish-codes
  email: me@finbytes.anonaddy.com
  links:
    - https://github.com/mish-codes

# Theme mode (dark/light/auto) — leave empty for auto
theme_mode:

# Collections
collections:
  tabs:
    output: true
    sort_by: order
  private:
    output: true
    permalink: /private/:name/
  quant_lab:
    output: true
    permalink: /quant-lab/:name/
  cpp:
    output: true
    permalink: /cpp/:name/

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
  - scope:
      path: ""
      type: cpp
    values:
      layout: cpp-post
      toc: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

future: true
